#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
pgrep -x light-locker > /dev/null || light-locker &
pgrep -x flameshot > /dev/null || flameshot &
pgrep -x picom > /dev/null || picom -b &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a code-oss desktop='6'
bspc rule -a firefox desktop='2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Script moved to monitor_setup
# $HOME/.config/polybar/launch.sh

$HOME/.config/bspwm/monitor_setup.sh

feh --bg-fill ~/.config/wallpapers/valley.jpg ~/.config/wallpapers/sunset_wide.jpg
