# Example item, with default values
# [[item]]
# file = '~/.config/example' (required)
# template = 'example' (required)
# subtemplate = 'default'
# rewrite = false
# start = '# Start flavours'
# end = '# End flavours'
# hook = ''

[[item]]
file = '~/dotfiles/rofi/.config/rofi/themes/colors.rasi'
template = 'rofi'
subtemplate = 'colors'
rewrite = true

[[item]]
file = '~/dotfiles/dunst/.config/dunst/dunstrc'
template = 'dunst'
rewrite = false
hook = 'killall dunst'

[[item]]
file = '~/dotfiles/kitty/.config/kitty/kitty.conf'
template = 'kitty'
rewrite = false
hook = 'kitty @ set_colors --all --configured ~/.config/kitty/kitty.conf'

[[item]]
file = '~/dotfiles/polybar/.config/polybar/colors.ini'
template = 'polybar'
rewrite = false
hook = 'polybar-msg cmd restart'

[[item]]
file = '~/dotfiles/vscode/.vscode-oss/extensions/namsnath.dotfile-theme-1.0.0/theme/dotfile-theme.json'
template = 'vscode'
rewrite = true